# Generated by Django 3.0.3 on 2020-02-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trans_type',
        ),
        migrations.AddField(
            model_name='categories',
            name='category_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expenditure', 'Expenditure')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
