# Generated by Django 3.0.3 on 2020-02-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanager', '0002_auto_20200221_1509'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
