# Generated by Django 3.0.3 on 2020-02-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanager', '0004_auto_20200221_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('t_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20)),
                ('category', models.CharField(choices=[('Bills', 'Bills'), ('Transportation', 'Transportation'), ('Shopping', 'Shopping'), ('Grocery', 'Grocery'), ('Daily Needs', 'Daily Needs'), ('Medical', 'Medical'), ('Other Expense', 'Other expense'), ('Salary', 'Salary'), ('Other Income', 'Other Income')], max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trans',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Trans',
        ),
    ]
